language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
matrix:
  fast_finish: true
stages:
  - lint
  - test
install: pip install tox codecov
jobs:
  include:
    - stage: lint
      script: tox -e lint
      python: "3.6"
script: tox -e coverage
after_success: codecov
