language: python
os: linux
python:
  - "3.6"
  - "3.7"
  - "3.8"
stages:
  - lint
  - check
  - test
install: pip install tox codecov
jobs:
  fast_finish: true
  include:
    - stage: lint
      script: tox -e lint
      python: "3.6"
    - stage: check
      script: tox -e check
      python: "3.6"
script: tox -e coverage
after_success: codecov
