language: python
python:
  - "3.6"
matrix:
  fast_finish: true
stages:
  - lint
  - test
install: pip install tox codecov
jobs:
  include:
    - stage: lint
      script: tox -e lint
script: tox -e coverage
after_success: codecov
