requires = [ "tox>=4.6" ]

[env_run_base]
runner = "uv-venv-runner"
package = "wheel"
dependency_groups = [ "dev", "tests" ]
commands = [ [ "pytest", { replace = "posargs", default = [ "--cov", "prometheus_aioexporter/" ], extend = true } ] ]

[env.check]
dependency_groups = [ "dev", "tests" ]
commands = [ [ "mypy", "prometheus_aioexporter", "tests", { replace = "posargs", default = [], extend = true } ] ]

[env.lint]
package = "skip"
dependency_groups = [ "dev" ]
commands = [ [ "pre-commit", "run", "--all-files" ] ]

[env.sample]
package = "editable"
commands = [
  [ "python", "-m", "prometheus_aioexporter.sample", { replace = "posargs", default = [], extend = true } ],
]
